In [45]:
import numpy as np

Concatenation means joining two arrays as a single array.It perform on existing axis does not create new axis.

In [46]:
# create 1 d array
array1=np.array([1,2,3])
array2=np.array([4,5,6])

In [47]:
np.concatenate((array1,array2)) # it merge array1 and array2 into single array

array([1, 2, 3, 4, 5, 6])

axis=0 means the merging along rows where no.columns must be match
axis= 1 means the merging along columns where no.of rows must be match 

In [48]:
np.concatenate((array1,array2),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

for 1d arrays axis=1 not present only axis=0 present thats why it produce axis error

In [ ]:
np.concatenate((array1,array2)).shape # rows of array1+rows of array2 =3+3=6

(6,)

In [ ]:
np.concatenate((array1,array2),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 1

In [ ]:
# create 2D array
array3=np.array([[1,2],[3,4]])
array4=np.array([[5,6],[7,8]])

In [ ]:
array3.shape,array4.shape

((2, 2), (2, 2))

In [ ]:
np.concatenate((array3,array4)) # default axis=0 means row wise

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((array3,array4)).shape 

(4, 2)

 (2,2),(2,2) shape of array3 and array 4 than resultant is row1+row2,column is 2+2,2=4,2

In [ ]:
np.concatenate((array3,array4),axis=1) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((array3,array4),axis=1).shape 

(2, 4)

(2,2) and (2,2) shape of array3 and array4 when you concatenate along axis=1 the resultant is rows,col1+col2 =2,2+2=(4,2 ) which is rows,2n

In [51]:
np.concatenate((array3,array4),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

axis=0 → the first dimension (size a)

axis=1 → the second dimension (size b)

axis=2 → the third dimension (size c)

for 1d array axis =0 present

for 2d array axis=0 and axis=1 is present 

for 3d array axis=2 is present it is last dimension


In [ ]:
# create 3d array
array5=np.array([[[1,2]],[[3,4]]])
array6=np.array([[[5,6]],[[7,8]]])

In [ ]:
np.shape(array5),np.shape(array6)

((2, 1, 2), (2, 1, 2))

In [ ]:
np.concatenate((array5,array6)).shape

(4, 1, 2)

(2,1,2) and (2,1,2) is shape of array6 and array7 then concatenation result along axis=0 is firstdimension of array5 + firstdimension of array6=(4,1,2) 

In [ ]:
np.concatenate((array5,array6),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [ ]:
np.concatenate((array5,array6),axis=1).shape

(2, 2, 2)

(2,1,2) and (2,1,2) are shapes of array5 and array 6 concatenation along axis=1 is secondhighest dimension of array5+secondhighestdimension of array6 =1+1=2 shape is 2,2,2 

In [ ]:



np.concatenate((array5,array6),axis=2)

array([[[1, 2, 5, 6]],

       [[3, 4, 7, 8]]])

concatenation along axis=2 is 

[row 0 of array5 ,row 0 of array6] # row0

[row 1 of array5 ,row  1 of array6] # row1      

[row  2 of array5 ,column 2 of array6] # row2 like wise axis=2 work


In [ ]:
np.concatenate((array5,array6),axis=2).shape

(2, 1, 4)

shape of array5 and array 6 is (2,1,2) concatenate along axis=2 is sumof last dimension of arrays is 2+2 is=4 remaining doesnot change then shape becomes (2,1,4)

In [ ]:



np.concatenate((array5,array6),axis=-1)

array([[[1, 2, 5, 6]],

       [[3, 4, 7, 8]]])

axis=-1 means last dimension of arrays which is axis=2 for 3d arrays and for 2d arrays axis=1