In [1]:
import numpy as np

In [16]:
# creating 1D array
array1=np.array([1,2,3])
array2=np.array([4,5,6])

In [17]:
np.stack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6]])

stack() method is used to joining array on new axis .along rows default axis=0 


In [18]:
# creating 1D array
array1=np.array([1,2,3])
array2=np.array([4,5,6])
array3=np.array([7,8,9])

In [19]:
np.stack((array1,array2)).shape # for 2 arrays 

(2, 3)

In [6]:
np.stack((array1,array2,array3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.stack((array1,array2,array3)).shape # for 3 arrays 

(3, 3)

shape for 1-d array joining arrays using stack on axis=0 is (no.of arrays),(no.of columns) above 3 arrays are presnt in each array 3 columns are present .the resultant shape is (3,3)

In [8]:
np.stack((array1,array2,array3),axis=1)



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
np.stack((array1,array2,array3),axis=1).shape

(3, 3)

In [20]:
np.stack((array1,array2,array3),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

for 1 d array axis=0 is present 

2d array is presnt after adding new dimension before 

3d array is not present

In [21]:
#create 2d array
array4=np.array([[1,2],[3,4]])
array5=np.array([[5,6],[7,8]])

In [ ]:
np.stack((array4,array5))

In [ ]:
np.stack((array4,array5)).shape

(2,2) are shapes of array 5 and array4 then resultant shape of stack along axis=0 is (no.arrays,rows,columns) (2,2,2) no.of arrays is 2

In [14]:
#create 2d array
array4=np.array([[1,2],[3,4]])
array5=np.array([[5,6],[7,8]])
array6=np.array([[9,10],[11,12]])

In [ ]:
np.stack((array4,array5,array6))

In [ ]:
np.stack((array4,array5,array6)).shape # here arrays are 3 then we conclude shape is (no.of arrays,shape of arras)

In [ ]:
np.stack((array4,array5,array6),axis=1)

In [ ]:
np.stack((array4,array5,array6),axis=1).shape

shape of array4,5,6 is 2,2 than joining of 3 arrays using stack method the resultant matrix shape is 
(rows,no.of arrays,no.of colums) (2,3,2)

In [ ]:
np.stack((array4,array5,array6),axis=2)

In [13]:
np.stack((array4,array5,array6),axis=2).shape

NameError: name 'array4' is not defined

shape of array4,array5,array6 is 2,2 joing along axis=2 is no.of rows,no.columns,no.of arrays is (2,2,3)

In [48]:
#create 3D arrays
array7=np.array([[[1,2]],[[3,4]]])
array8=np.array([[[5,6]],[[7,8]]])
array9=np.array([[[9,10]],[[11,12]]])

In [49]:
np.stack((array7,array8,array9))

array([[[[ 1,  2]],

        [[ 3,  4]]],


       [[[ 5,  6]],

        [[ 7,  8]]],


       [[[ 9, 10]],

        [[11, 12]]]])

In [50]:
np.stack((array7,array8,array9)).shape

(3, 2, 1, 2)

In [51]:
np.stack((array7,array8,array9),axis=1)

array([[[[ 1,  2]],

        [[ 5,  6]],

        [[ 9, 10]]],


       [[[ 3,  4]],

        [[ 7,  8]],

        [[11, 12]]]])

In [52]:
np.stack((array7,array8,array9),axis=1).shape

(2, 3, 1, 2)

In [53]:
np.stack((array7,array8,array9),axis=2)

array([[[[ 1,  2],
         [ 5,  6],
         [ 9, 10]]],


       [[[ 3,  4],
         [ 7,  8],
         [11, 12]]]])

In [54]:
np.stack((array7,array8,array9),axis=2).shape

(2, 1, 3, 2)

In [55]:
np.stack((array7,array8,array9),axis=3)

array([[[[ 1,  5,  9],
         [ 2,  6, 10]]],


       [[[ 3,  7, 11],
         [ 4,  8, 12]]]])

In [56]:
np.stack((array7,array8,array9),axis=3).shape

(2, 1, 2, 3)

In [57]:
array1,array2,array3

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [58]:
np.hstack((array1,array2,array3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.hstack((array1,array2,array3)).shape

(9,)

hstack() method is use to combine arrays side by side (along columns) in a quick, readable way same like as concatenation which axis=0

In [60]:
np.hstack((array1,array2,array3),axis=1)

TypeError: hstack() got an unexpected keyword argument 'axis'

In [61]:
array4,array5,array6

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [66]:



np.hstack((array4,array5,array6))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [67]:
np.hstack((array4,array5,array6)).shape

(2, 6)

In [63]:
array7,array8,array9

(array([[[1, 2]],
 
        [[3, 4]]]),
 array([[[5, 6]],
 
        [[7, 8]]]),
 array([[[ 9, 10]],
 
        [[11, 12]]]))

In [64]:
array7.shape

(2, 1, 2)

In [65]:
np.hstack((array7,array8,array9))

array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]],

       [[ 3,  4],
        [ 7,  8],
        [11, 12]]])

In [68]:
np.hstack((array7,array8,array9)).shape

(2, 3, 2)

np.hstack = np.concatenate(..., axis=1)
(except for 1D arrays, where it behaves like simple concatenation).

Always along axis=1

If array has n ≥ 2 dimensions, it concatenates along the second axis.

If array has n = 1 dimension, there is no axis 1 → so it just flattens them into a single row

In [69]:
array1,array2,array3

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [70]:
np.vstack((array1,array2,array3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

vstack() method it join arrays along rows means it is same as np.concatenate((arrays),axis=0)


In [71]:
np.vstack((array1,array2,array3)).shape

(3, 3)

In [72]:
np.vstack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.vstack((array1,array2)).shape

(2, 3)

ths shape of resultant vstack() is sum of first dimension of all arrays . for 1D array (no.of arrays,shape ) is shape of array1,array2 is (3,) then resultant is (2,3)

In [75]:
np.vstack((array1,array2),axis=1)

TypeError: vstack() got an unexpected keyword argument 'axis'

In [76]:
array4,array5,array6

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [77]:
np.vstack((array4,array5,array6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [78]:
np.vstack((array4,array5,array6)).shape

(6, 2)

if arrays are 2D then shape is (sum of first dimension of all arrays ,all other dimensions same) .
(2,2) shape of array4,array5,array6 then result is 2+2+2=6 6,2 is resultant


In [79]:
array7,array8,array9

(array([[[1, 2]],
 
        [[3, 4]]]),
 array([[[5, 6]],
 
        [[7, 8]]]),
 array([[[ 9, 10]],
 
        [[11, 12]]]))

In [80]:
np.vstack((array7,array8,array9))

array([[[ 1,  2]],

       [[ 3,  4]],

       [[ 5,  6]],

       [[ 7,  8]],

       [[ 9, 10]],

       [[11, 12]]])

In [81]:
np.vstack((array7,array8,array9)).shape

(6, 1, 2)

In [83]:
array1,array2,array3

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [84]:
np.dstack((array1,array2,array3))

array([[[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]])

In [85]:
np.dstack((array1,array2,array3)).shape

(1, 3, 3)

In [86]:
array4,array5,array6

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [87]:
np.dstack((array4,array5,array6))

array([[[ 1,  5,  9],
        [ 2,  6, 10]],

       [[ 3,  7, 11],
        [ 4,  8, 12]]])

In [88]:
np.dstack((array4,array5,array6)).shape

(2, 2, 3)

In [89]:
array7,array8,array9

(array([[[1, 2]],
 
        [[3, 4]]]),
 array([[[5, 6]],
 
        [[7, 8]]]),
 array([[[ 9, 10]],
 
        [[11, 12]]]))

In [90]:
np.dstack((array7,array8,array9))

array([[[ 1,  2,  5,  6,  9, 10]],

       [[ 3,  4,  7,  8, 11, 12]]])

In [91]:
np.dstack((array7,array8,array9)).shape

(2, 1, 6)

dtack()-> is same as np.concatenate(tup,axis=2).

for 1-D arrays the resultant dstack is - (1,no.of elements,no.of arrays)

for 2-D arrays the resultant dstack is - (no.of rows,no.of columns,no.of arrays)

for 3D and above the resultant dstack is - (first dimension,second dimension,sum of 3rd dimension all arrays )

In [92]:
array1,array2,array3

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [93]:
np.column_stack((array1,array2,array3))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [94]:
np.column_stack((array1,array2,array3)).shape

(3, 3)

In [95]:
array4,array5,array6

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [98]:
np.column_stack((array4,array5,array6))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

column_stack() is same as hstack() but h_stack for multiple 1D arrays result is 1D array but column_stack change 2D array this is key_difference between column and hstack. 2D and above same as hstack 

In [100]:
np.column_stack((array4,array5,array6)).shape

(2, 6)

In [101]:
array7,array8,array9

(array([[[1, 2]],
 
        [[3, 4]]]),
 array([[[5, 6]],
 
        [[7, 8]]]),
 array([[[ 9, 10]],
 
        [[11, 12]]]))

In [102]:
np.column_stack((array7,array8,array9))

array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]],

       [[ 3,  4],
        [ 7,  8],
        [11, 12]]])

In [103]:
np.column_stack((array7,array8,array9)).shape

(2, 3, 2)