In [1]:
import numpy as np

In [16]:
# creating 1D array
array1=np.array([1,2,3])
array2=np.array([4,5,6])

In [17]:
np.stack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6]])

stack() method is used to joining array on new axis .along rows default axis=0 


In [18]:
# creating 1D array
array1=np.array([1,2,3])
array2=np.array([4,5,6])
array3=np.array([7,8,9])

In [19]:
np.stack((array1,array2)).shape # for 2 arrays 

(2, 3)

In [6]:
np.stack((array1,array2,array3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.stack((array1,array2,array3)).shape # for 3 arrays 

(3, 3)

shape for 1-d array joining arrays using stack on axis=0 is (no.of arrays),(no.of columns) above 3 arrays are presnt in each array 3 columns are present .the resultant shape is (3,3)

In [8]:
np.stack((array1,array2,array3),axis=1)



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
np.stack((array1,array2,array3),axis=1).shape

(3, 3)

In [20]:
np.stack((array1,array2,array3),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

for 1 d array axis=0 is present 

2d array is presnt after adding new dimension before 

3d array is not present

In [21]:
#create 2d array
array4=np.array([[1,2],[3,4]])
array5=np.array([[5,6],[7,8]])

In [ ]:
np.stack((array4,array5))

In [ ]:
np.stack((array4,array5)).shape

(2,2) are shapes of array 5 and array4 then resultant shape of stack along axis=0 is (no.arrays,rows,columns) (2,2,2) no.of arrays is 2

In [14]:
#create 2d array
array4=np.array([[1,2],[3,4]])
array5=np.array([[5,6],[7,8]])
array6=np.array([[9,10],[11,12]])

In [ ]:
np.stack((array4,array5,array6))

In [ ]:
np.stack((array4,array5,array6)).shape # here arrays are 3 then we conclude shape is (no.of arrays,shape of arras)

In [ ]:
np.stack((array4,array5,array6),axis=1)

In [ ]:
np.stack((array4,array5,array6),axis=1).shape

shape of array4,5,6 is 2,2 than joining of 3 arrays using stack method the resultant matrix shape is 
(rows,no.of arrays,no.of colums) (2,3,2)

In [ ]:
np.stack((array4,array5,array6),axis=2)

In [13]:
np.stack((array4,array5,array6),axis=2).shape

NameError: name 'array4' is not defined

shape of array4,array5,array6 is 2,2 joing along axis=2 is no.of rows,no.columns,no.of arrays is (2,2,3)

In [22]:
#create 3D arrays
array7=[[[1,2]],[[3,4]]]
array8=[[[5,6]],[[7,8]]]
array9=[[[9,10]],[[11,12]]]

In [23]:
np.stack((array7,array8,array9))

array([[[[ 1,  2]],

        [[ 3,  4]]],


       [[[ 5,  6]],

        [[ 7,  8]]],


       [[[ 9, 10]],

        [[11, 12]]]])

In [24]:
np.stack((array7,array8,array9)).shape

(3, 2, 1, 2)

In [25]:
np.stack((array7,array8,array9),axis=1)

array([[[[ 1,  2]],

        [[ 5,  6]],

        [[ 9, 10]]],


       [[[ 3,  4]],

        [[ 7,  8]],

        [[11, 12]]]])

In [26]:
np.stack((array7,array8,array9),axis=1).shape

(2, 3, 1, 2)

In [33]:
np.stack((array7,array8,array9),axis=2)

array([[[[ 1,  2],
         [ 5,  6],
         [ 9, 10]]],


       [[[ 3,  4],
         [ 7,  8],
         [11, 12]]]])

In [31]:
np.stack((array7,array8,array9),axis=2).shape

(2, 1, 3, 2)

In [28]:
np.stack((array7,array8,array9),axis=3)

array([[[[ 1,  5,  9],
         [ 2,  6, 10]]],


       [[[ 3,  7, 11],
         [ 4,  8, 12]]]])

In [29]:
np.stack((array7,array8,array9),axis=3).shape

(2, 1, 2, 3)